name: Purge README
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/purge-readme@v1
  	with:
    	    repo: wow-actions/purge-readme
    	    branch: master
    	    paths: |
      	    	README.md
      		images.md
